# Generated by Django 5.2.8 on 2026-08-28 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0022_groupmembership_driver_license_number_and_more'),
        ('user', '0008_customuser_email'),
        ('wallet', '0015_wallet_is_platform_treasury_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='enable_recurring_contributions',
            field=models.BooleanField(default=False, help_text='Whether this group collects recurring scheduled contributions'),
        ),
        migrations.AddField(
            model_name='group',
            name='recurring_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount expected per member per cycle', max_digits=10),
        ),
        migrations.AddField(
            model_name='group',
            name='recurring_due_day',
            field=models.PositiveSmallIntegerField(default=25, help_text='Day of the month dues are expected (1-31)'),
        ),
        migrations.AddField(
            model_name='group',
            name='recurring_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('annual', 'Annual')], default='monthly', help_text='Cycle frequency for recurring dues', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='recurring_reminder_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Days prior to due date to send reminder notification'),
        ),
        migrations.AddField(
            model_name='group',
            name='recurring_title',
            field=models.CharField(blank=True, default='Monthly Contribution', help_text='Descriptive title for recurring cycles (e.g. Monthly Dues, Stokvel Pool)', max_length=150),
        ),
        migrations.CreateModel(
            name='ContributionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField(help_text='Contribution deadline for this cycle')),
                ('target_amount_per_member', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed amount expected from each active member', max_digits=10)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active (Open for Payment)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('cycle_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cycle_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_cycles', to='chema.group')),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
                'unique_together': {('group', 'cycle_month', 'cycle_year')},
            },
        ),
        migrations.CreateModel(
            name='MemberCyclePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('exempt', 'Exempt / Waived')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('wallet', 'Wallet Balance'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('other', 'Other')], default='wallet', max_length=50)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='chema.contributioncycle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_payments', to='user.profile')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_payment', to='wallet.transaction')),
            ],
            options={
                'ordering': ['status', 'member__first_name', 'member__surname'],
                'unique_together': {('cycle', 'member')},
            },
        ),
    ]
