# Generated by Django 5.2.8 on 2026-09-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0023_group_enable_recurring_contributions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='purpose',
            field=models.CharField(choices=[('bereavement', 'Bereavement Fund'), ('excess', 'Insurance Excess Fund'), ('emergency', 'Emergency / Disaster Fundraiser'), ('custom', 'Custom Fund'), ('church', 'Church / Religious Group'), ('stokvel', 'Stokvel & Rotating Savings'), ('student', 'Student Body & Society')], default='bereavement', help_text='The primary fund-pooling purpose of this group', max_length=20),
        ),
        migrations.DeleteModel(
            name='GroupSportsProfile',
        ),
    ]
