# Generated by Django 5.2.8 on 2026-09-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0024_alter_group_purpose_delete_groupsportsprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_pbo_registered',
            field=models.BooleanField(default=False, help_text='Whether this group is a SARS-approved Public Benefit Organisation (PBO)'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_section_18a_approved',
            field=models.BooleanField(default=False, help_text='Approved by SARS to issue Section 18A tax-deductible donation receipts'),
        ),
        migrations.AddField(
            model_name='group',
            name='pbo_reference_number',
            field=models.CharField(blank=True, help_text='SARS PBO Tax Exemption reference number (e.g. 930012345)', max_length=50, null=True),
        ),
    ]
