# Generated by Django 5.2.8 on 2026-09-09 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_wallet_is_platform_treasury_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(help_text='Flutterwave/Gateway customer ID', max_length=120)),
                ('payment_method_id', models.CharField(help_text='Flutterwave/Gateway tokenized payment method ID', max_length=120)),
                ('card_brand', models.CharField(default='Visa', help_text='Card brand e.g. Visa, Mastercard', max_length=50)),
                ('last4', models.CharField(help_text='Last 4 digits of card', max_length=4)),
                ('expiry_month', models.CharField(help_text='MM', max_length=2)),
                ('expiry_year', models.CharField(help_text='YY or YYYY', max_length=4)),
                ('cardholder_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
