# Generated by Django 5.2.8 on 2026-09-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_savedcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformfeeconfig',
            name='admin_alert_email',
            field=models.EmailField(blank=True, default='', help_text='Admin email for high-value FICA threshold breaches and reconciliation notices', max_length=254),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='admin_alert_phone',
            field=models.CharField(blank=True, default='', help_text='Mobile number for urgent SMS compliance & treasury notifications', max_length=30),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='daily_user_transfer_limit',
            field=models.DecimalField(decimal_places=2, default=50000.0, help_text='Maximum daily transfer/payout volume per user wallet (ZAR)', max_digits=12),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='fica_reporting_threshold',
            field=models.DecimalField(decimal_places=2, default=25000.0, help_text='FICA Cash Threshold Reporting (CTR) & high-value transaction alert limit (ZAR)', max_digits=12),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='is_maintenance_mode',
            field=models.BooleanField(default=False, help_text='Emergency platform kill-switch / maintenance mode toggle'),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='is_vat_registered',
            field=models.BooleanField(default=False, help_text='Enable once Komunity is registered as a VAT Vendor with SARS (Mandatory if turnover exceeds R1,000,000 in 12 months)'),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='max_single_payout',
            field=models.DecimalField(decimal_places=2, default=30000.0, help_text='Maximum single payout/withdrawal amount allowed per transaction (ZAR)', max_digits=12),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='registered_business_address',
            field=models.TextField(blank=True, default='Johannesburg, Gauteng, South Africa', help_text='Official legal/tax physical address displayed on invoices and receipts'),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='registered_business_name',
            field=models.CharField(default='Komunity (Pty) Ltd', help_text='Official registered entity name with CIPC and SARS', max_length=150),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='sars_tax_number',
            field=models.CharField(blank=True, default='', help_text='SARS Corporate Income Tax reference number', max_length=20),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='tax_year_end_month',
            field=models.PositiveSmallIntegerField(default=2, help_text='SARS Corporate Tax Year End Month (2 = February for standard South African company tax year)'),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Standard South African VAT rate (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='vat_pricing_mode',
            field=models.CharField(choices=[('INCLUSIVE', 'VAT Inclusive (Platform fees include 15% VAT)'), ('EXCLUSIVE', 'VAT Exclusive (15% VAT added on top of fee)')], default='INCLUSIVE', help_text='How VAT is factored into platform transaction fees', max_length=15),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='vat_registration_number',
            field=models.CharField(blank=True, default='', help_text='SARS 10-digit VAT registration number (e.g. 4012345678)', max_length=20),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='vat_threshold_amount',
            field=models.DecimalField(decimal_places=2, default=1000000.0, help_text='SARS Compulsory VAT Registration Threshold (ZAR 1,000,000)', max_digits=12),
        ),
        migrations.AddField(
            model_name='platformfeeledger',
            name='net_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Net fee income to Komunity excluding VAT (Gross revenue for Corporate Income Tax)', max_digits=12),
        ),
        migrations.AddField(
            model_name='platformfeeledger',
            name='tax_year',
            field=models.CharField(blank=True, default='', help_text="SARS Tax Year (e.g. '2026/2027') for auditing", max_length=15),
        ),
        migrations.AddField(
            model_name='platformfeeledger',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Output VAT portion of the platform fee owed to SARS', max_digits=12),
        ),
        migrations.AddField(
            model_name='platformfeeledger',
            name='vat_rate_applied',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='VAT rate (%) applied at transaction time', max_digits=5),
        ),
    ]
