# Generated by Django 5.2.8 on 2026-09-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0025_group_is_pbo_registered_and_more'),
        ('condolence', '0006_allow_multiple_campaign_contributions'),
        ('wallet', '0017_platformfeeconfig_admin_alert_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('TOP_UP', 'Top-Up'), ('TRANSFER', 'Transfer to Group'), ('WITHDRAWAL', 'Withdrawal'), ('PAYOUT_RECEIVED', 'Payout Received'), ('P2P_SENT', 'Peer-to-Peer Sent'), ('P2P_RECEIVED', 'Peer-to-Peer Received'), ('SMS_PACKAGE_PURCHASE', 'SMS Package Purchase'), ('PLATFORM_FEE_COLLECTED', 'Platform Fee Revenue')], db_index=True, max_length=35),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'status', '-timestamp'], name='wallet_tran_wallet__ea175e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='wallet_tran_transac_019d56_idx'),
        ),
    ]
